string1 = 'Olá '
string2 = 'mundo!'
string3 = 'amor' * 4
string4 = '-'
string5 = 'O céu é azul.'
string6 = '  Sim.'
string7 = 'pessoa1, pessoa2, pessoa3'

print('OPERAÇÕES COM STRINGS')
print(f'string1 "Olá ": {string1}')
print(f'string2: {string2}')
print(f'string3 "amor" * 4: {string3}')
print(f'string4: {string4}')
print(f'string5: {string5}')
print(f'string6 "  Sim.": {string6}')
print(f'string7: {string7}')
print('-----------------------------------------')
print(f'1 valor da string5.title(): {string5.title()}')
print(f'2 valor da string1: {string1}')
print(f'3 valor da string1 + string2: {string1 + string2}')
print(f'4 valor da string3: {string3}')
print(f'5 valor da string4 * 20: {string4 * 20}')
print(f'6 valor da string1.lower: {string1.lower()}')
print(f'7 valor da string1.upper: {string1.upper()}')
print(f'8 fatiamento da string5 = string5[0:5]: {string5[0:5]}')
print(f'9 string6: {string6}')
print(f'10 string6.strip(): {string6.strip()}')
print(f'11 valor da string7: {string7}')
print(f'12 string7[0:7] {string7[0:7]}')
print(f'13 string7.split(", ") {string7.split(', ')}')
print(f'14 string7.split(", ")[0] {string7.split(', ')[0]}')
print(f'15 string7.split(", ")[1] {string7.split(', ')[1]}')
print('16 type(string7), type(string7.split(", "))' , type(string7), type(string7.split(', ')))
print('17 type(string7), type(string7.split(", ")[0])',  type(string7), type(string7.split(', ')[0]))
lista = ['1','2','3']
print('18 lista: ', lista)
print('19 ";".join(lista)', ';'.join(lista))
print('20 type(";".join(lista))', type(';'.join(lista)))
print('21 "\n".join(lista)', '\n'.join(lista))
print('22 len(string7)', len(string7))
print('23 string7.count("s")', string7.count('s'))
print('24 string7.replace("pessoa", "p")', string7.replace('pessoa', 'p'))
print('25 string7.startswith("p")', string7.startswith('p'))
print('26 string7.startswith("a")', string7.startswith('a'))
print('27 string7.startswith("pessoa")', string7.startswith('pessoa'))
print('28 string7.endswith("a")', string7.endswith('a'))
print('29 string7.endswith("3")', string7.endswith('3'))
print('30 "2" in string7', '2' in string7)
print('31 "pessoa" in string7', 'pessoa' in string7)

print('\n CONVERSÕES DE STRING')
inteiro_str = float('1')
print('32 inteiro_str, type(inteiro_str)', inteiro_str, type(inteiro_str))
bool_str = bool('1')
print('33 bool_str, type(bool_str)', bool_str, type(bool_str))
print()
print('De str -> bool: qualquer string que não seja vazia é true')
bool_str2 = bool('amor')
print('34 bool_str2, type(bool_str2)', bool_str2, type(bool_str2))
bool_str3 = bool('')
print('35 bool_str3, type(bool_str3)', bool_str3, type(bool_str3))

numero = int(input('36 Digite um número: '))
print(f'37 O número que você digitou é: {numero + 5}. O tipo é {type(numero)}.')

print('38')
print('Mensagem')
print('Mensagem2')
print('---')
print('"Mensagem", end="teste"')
print('Mensagem', end='teste')
print('Mensagem2')